-- AlterTable
ALTER TABLE "VendorProfile" ADD COLUMN     "avgRating" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "cancellationRate" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "followerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qualityScore" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "shippingScore" INTEGER NOT NULL DEFAULT 100;
