// data/productsData.js

export const ProductsData = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    image: "/images/products/headphones.jpg",
    price: 59.99,
    oldPrice: 89.99,
    category: "Electronics",
    rating: 4.5,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
  },
  {
    id: 2,
    name: "Classic Leather Backpack",
    image: "/images/products/backpack.jpg",
    price: 74.99,
    oldPrice: null,
    category: "Fashion",
    rating: 4.8,
    isFeatured: true,
    isNew: true,
    isOnSale: false,
  },
  {
    id: 3,
    name: "Smart Fitness Watch",
    image: "/images/products/watch.jpg",
    price: 99.99,
    oldPrice: 129.99,
    category: "Wearables",
    rating: 4.3,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
  },
  {
    id: 4,
    name: "Modern Table Lamp",
    image: "/images/products/lamp.jpg",
    price: 39.99,
    oldPrice: null,
    category: "Home Decor",
    rating: 4.2,
    isFeatured: true,
    isNew: true,
    isOnSale: false,
  },
  {
    id: 5,
    name: "Running Sneakers",
    image: "/images/products/sneakers.jpg",
    price: 69.99,
    oldPrice: 89.99,
    category: "Shoes",
    rating: 4.7,
    isFeatured: true,
    isNew: false,
    isOnSale: true,
  },
];
