/* ===========================================================
 * AUDIT ACTIONS
 * =========================================================== */

export enum AuditAction {
  ADMIN_CREATED = "ADMIN_CREATED",
  ADMIN_UPDATED = "ADMIN_UPDATED",
  ADMIN_DELETED = "ADMIN_DELETED",

  ROLE_CHANGED = "ROLE_CHANGED",

   USER_UPDATED = "USER_UPDATED",

  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_DELETED = "PRODUCT_DELETED",

  CATEGORY_CREATED = "CATEGORY_CREATED",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_DELETED = "CATEGORY_DELETED",

  ORDER_CREATED = "ORDER_CREATED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  ORDER_REFUNDED = "ORDER_REFUNDED",
  ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED",

  VENDOR_APPROVED = "VENDOR_APPROVED",
  VENDOR_REJECTED = "VENDOR_REJECTED",
  VENDOR_SUSPENDED = "VENDOR_SUSPENDED",
  VENDOR_UNSUSPENDED = "VENDOR_UNSUSPENDED",
  VENDOR_UPDATED = "VENDOR_UPDATED",

  PAYOUT_APPROVED = "PAYOUT_APPROVED",
  PAYOUT_REJECTED = "PAYOUT_REJECTED",

  WALLET_FUNDED = "WALLET_FUNDED",
  WALLET_WITHDRAWN = "WALLET_WITHDRAWN",


}

/* ===========================================================
 * AUTH ACTIONS
 * =========================================================== */

export enum AuthAction {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",

  LOGOUT = "LOGOUT",

  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",

  CUSTOMER_REGISTERED = "CUSTOMER_REGISTERED",
  VENDOR_REGISTERED = "VENDOR_REGISTERED",

  CUSTOMER_VERIFIED = "CUSTOMER_VERIFIED",
  VENDOR_VERIFIED = "VENDOR_VERIFIED",
}




/* ===========================================================
 * SECURITY EVENTS
 * =========================================================== */

export enum SecurityEvent {
  CSRF_BLOCKED = "CSRF_BLOCKED",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INVALID_TOKEN = "INVALID_TOKEN",

  PERMISSION_DENIED = "PERMISSION_DENIED",

  INVALID_PAYMENT = "INVALID_PAYMENT",

  WEBHOOK_SIGNATURE_FAILED = "WEBHOOK_SIGNATURE_FAILED",

  REPLAY_ATTACK = "REPLAY_ATTACK",

  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
}


