/* ===========================================================
 * AUDIT ACTIONS
 * =========================================================== */

export enum AuditAction {
  ADMIN_CREATED = "ADMIN_CREATED",
  ADMIN_UPDATED = "ADMIN_UPDATED",
  ADMIN_DELETED = "ADMIN_DELETED",

  ROLE_CHANGED = "ROLE_CHANGED",

  USER_UPDATED = "USER_UPDATED",

  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_DELETED = "PRODUCT_DELETED",
  PRODUCT_PUBLICATION_CHANGED = "PRODUCT_PUBLICATION_CHANGED",
  PRODUCT_TRENDING_CHANGED = "PRODUCT_TRENDING_CHANGED",
  PRODUCT_FLAGS_BULK_CHANGED = "PRODUCT_FLAGS_BULK_CHANGED",

  REVIEW_APPROVAL_CHANGED = "REVIEW_APPROVAL_CHANGED",
  REVIEWS_BULK_APPROVAL_CHANGED = "REVIEWS_BULK_APPROVAL_CHANGED",
  REVIEWS_BULK_DELETED = "REVIEWS_BULK_DELETED",
  REVIEW_DELETED = "REVIEW_DELETED",

  VARIANT_CREATED = "VARIANT_CREATED",
  VARIANT_DELETED = "VARIANT_DELETED",
  PRODUCT_IMAGE_ADDED = "PRODUCT_IMAGE_ADDED",
  PRODUCT_IMAGES_ADDED = "PRODUCT_IMAGES_ADDED",
  PRODUCT_IMAGE_DELETED = "PRODUCT_IMAGE_DELETED",

  CATEGORY_CREATED = "CATEGORY_CREATED",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_DELETED = "CATEGORY_DELETED",

  ORDER_CREATED = "ORDER_CREATED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  ORDER_REFUNDED = "ORDER_REFUNDED",
  REFUND_REQUESTED = "REFUND_REQUESTED",
  REFUND_APPROVED = "REFUND_APPROVED",
  REFUND_REJECTED = "REFUND_REJECTED",
  ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED",

 

  VENDOR_APPROVED = "VENDOR_APPROVED",
  VENDOR_REJECTED = "VENDOR_REJECTED",
  VENDOR_SUSPENDED = "VENDOR_SUSPENDED",
  VENDOR_UNSUSPENDED = "VENDOR_UNSUSPENDED",
  VENDOR_UPDATED = "VENDOR_UPDATED",

  PAYOUT_REQUESTED = "PAYOUT_REQUESTED",
  PAYOUT_APPROVED = "PAYOUT_APPROVED",
  PAYOUT_REJECTED = "PAYOUT_REJECTED",
  PAYOUT_FINALIZED = "PAYOUT_FINALIZED",

  WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED",

  COURIER_CREATED = "COURIER_CREATED",
  COURIER_UPDATED = "COURIER_UPDATED",
  COURIER_STATUS_CHANGED = "COURIER_STATUS_CHANGED",

  WALLET_FUNDED = "WALLET_FUNDED",
  WALLET_WITHDRAWN = "WALLET_WITHDRAWN",

  VENDOR_BOOST_CREDITS_PURCHASED =
    "VENDOR_BOOST_CREDITS_PURCHASED",





}

/* ===========================================================
 * AUTH ACTIONS
 * =========================================================== */

export enum AuthAction {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",

  LOGOUT = "LOGOUT",

  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",

  CUSTOMER_REGISTERED = "CUSTOMER_REGISTERED",
  VENDOR_REGISTERED = "VENDOR_REGISTERED",

  CUSTOMER_VERIFIED = "CUSTOMER_VERIFIED",
  VENDOR_VERIFIED = "VENDOR_VERIFIED",
}




/* ===========================================================
 * SECURITY EVENTS
 * =========================================================== */

export enum SecurityEvent {
  CSRF_BLOCKED = "CSRF_BLOCKED",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INVALID_TOKEN = "INVALID_TOKEN",

  PERMISSION_DENIED = "PERMISSION_DENIED",

  INVALID_PAYMENT = "INVALID_PAYMENT",

  WEBHOOK_SIGNATURE_FAILED = "WEBHOOK_SIGNATURE_FAILED",

  REPLAY_ATTACK = "REPLAY_ATTACK",

  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
}


