-- CreateEnum
CREATE TYPE "BoostPlan" AS ENUM ('FREE', 'BASIC', 'PRO', 'ULTRA');

-- AlterTable
ALTER TABLE "VendorBoost" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "plan" "BoostPlan" NOT NULL DEFAULT 'FREE',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
